version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "127.0.0.1:53306:3306"
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev0000
      - MYSQL_ROOT_PASSWORD=root0000
